name: "Flutter PR Checks"
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
  		with:
		  flutter-version: '3.7.12'
		  channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - uses: c-hive/gha-yarn-cache@v2

      - name: Run Danger
        run: |
          cd $GITHUB_WORKSPACE
          yarn add danger --dev
          yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
